### PR TITLE
New style USIs

### PR DESCRIPTION
**Pull request by bittremieux**

### CODE REVIEW

**Comment by bittremieux** [comment]
Bleh, I still need to update the unit tests. That's for tomorrow.

**Comment by bittremieux** [comment]
Updated code also does error checking as per #47, except for time-outs.

**Comment by mwang87** [comment]
Made a few more warnings. Before we merge and deploy, will need to coordinate with other resources to roll them out.

**Comment by bittremieux** [comment]
I've differentiated between official USIs and our metabolomics USIs. For the official ones we should still use the `mzspec` prefix imo to have cross-platform compatibility with resources the proteomics repositories will develop.

Maybe we should document for the users when and for which repositories they need to use `mzspec` and `mzdraft` though?

**Comment by bittremieux** [comment]
There's also something going on in this PR that the production tests always time out? 🤔

**Comment by mwang87** [comment]
Can be tested here: 

http://dorresteintesthub.ucsd.edu:5087/

**Comment by mwang87** [comment]
Updated so no conflicts and deployed here:

http://dorresteintesthub.ucsd.edu:5087/

**Pull request merged**
