### PR TITLE
Better cosine score + annotate custom peaks

### LINKED ISSUE #78: Is cosine similarity working correctly?
This example is a bit baffling:
https://metabolomics-usi.ucsd.edu/mirror/?usi1=mzspec:MASSBANK:PB000417&usi2=mzspec:MS2LDATASK-1198:document:1628659
Any thoughts?

### PR DESCRIPTION
**Pull request by bittremieux**
Fixes #78.

### CODE REVIEW

**Comment by bittremieux** [comment]
Argh, I wanted to open a new PR with functionality to annotate custom peaks, but Github just added the new commits to this PR. 🤷‍♂️

Addresses #76.

This still needs to be extended with similar functionality for mirror plots.

@mwang87 Do you have any idea why I can't seem to make the toggle in `drawing_controls.html` line 54 work?

**Comment by bittremieux** [comment]
Ok, toggle fixed. The jQuery version was just too old. Could have saved me some frustration.

**Comment by mwang87** [comment]
I like the added functionality, but I kind of miss the simplicity of the previous thresholds with the autolabeling. If too hard to have the previous as a default, then we can just go with this. This is super fancy though I can see it being super annoying when the number of peaks gets large.

**Comment by bittremieux** [comment]
Blame @lfnothias in #76. ^^

It's not hard to label some peaks by default, but it's a bit annoying to keep the peak checkboxes and the figure in sync in that case.

**Comment by sdrogers** [comment]
Has the new cosine fixed the example I showed for you guys?
Doesn't seem to have fixed it for me...

**Comment by sdrogers** [comment]
> Has the new cosine fixed the example I showed for you guys?
> Doesn't seem to have fixed it for me...

Ignore that - my bad - got in a docker build muddle

Suggest we pull the cosine thing ASAP as people may be using it, and the low values are a bit misleading (esp as they can be a long way away from scores generated in, say, GNPS)

**Comment by mwang87** [comment]
@sdrogers yes, let me get it sorted out today with Wout on the peak labeling as well. If its good, we can just deploy and push it out there.

**Comment by mwang87** [comment]
Sorry for delay, fixed bug I identified and added tests for it.

**Comment by bittremieux** [comment]
Looks good, go for it! 👍

**Pull request merged**
