### PR TITLE
Fixing testing by allowing longer tolerances

### PR DESCRIPTION
**Pull request by mwang87**
Increase from 7 seconds to 20 seconds, we will turn this back down once we dial the resources in on new server.

### CODE REVIEW

**Review by bittremieux — COMMENTED** [review]
This just changes the timeout for the tests. Retrieving spectra will still fail (and hence the tests will fail) if it exceeds the shorter [timeout during third-party retrieval](https://github.com/mwang87/MetabolomicsSpectrumResolver/blob/master/parsing.py#L14), so I recommend increasing that (temporarily) as well. The main timeout culprit is MassIVE in my experience.

**Comment by mwang87** [comment]
> This just changes the timeout for the tests. Retrieving spectra will still fail (and hence the tests will fail) if it exceeds the shorter [timeout during third-party retrieval](https://github.com/mwang87/MetabolomicsSpectrumResolver/blob/master/parsing.py#L14), so I recommend increasing that (temporarily) as well. The main timeout culprit is MassIVE in my experience.

Its a good point, but both things caused issues on the GitHub actions side. I think what was happening at least in my testing is we were flooding with more requests than the server could handle and the median response was a bit under 20 seconds with few failures.

**Comment by bittremieux** [comment]
Hmm, why is the unit test for the MassIVE task USI failing?

**Comment by mwang87** [comment]
Oh is it haha! Let me take a deeper look there then!

**Pull request merged**
